### ISSUE TITLE
Why nested query works but not nested mutations ?!

### ISSUE THREAD

**Issue by alimoezzi** [flipbit03/sqlalchemy-graphql-schemagen#3]
For example nested objects like the following does appear in query schema 
![image](https://user-images.githubusercontent.com/37932944/89757494-a699d500-dafa-11ea-83d4-3edd680d2068.png)
But not appearing in create or update mutation schema like the following
![image](https://user-images.githubusercontent.com/37932944/89757567-e365cc00-dafa-11ea-8a79-5f13c90a76c7.png)

**Comment by flipbit03** [comment]
The lib maps directly to the underlying sqlalchemy schema.

When mutating an object, if you updated fields on the related tables, you would be updating data on a table/instance **different** from the method used to mutate data.

when selecting, the relationships are provided since the links are already available and you are not mutating any data.

**Comment by alimoezzi** [comment]
Can this be supported ?

**Comment by flipbit03** [comment]
It cannot be supported in any stable way because editing other **related** objects would break the proper scoping of your call.

if you are mutating "X" object, it would not be okay to have access to also edit "Y" structures (that might be linked to other objects).
